global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend-service:5000"]

  - job_name: "flask-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["flask-service:8000"]
